version: '3'
services:
  jupyter:
    image: quay.io/jupyter/datascience-notebook
    # image: quay.io/jupyter/scipy-notebook
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    command: "start-notebook.sh --ServerApp.root_dir=/home/jovyan/work --NotebookApp.token="
