version: '3'
services:
  jupyter:
    image: quay.io/jupyter/scipy-notebook
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    command: "start-notebook.sh --NotebookApp.token="
